/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pragmaticobjects.oo.data.model.source;

import com.pragmaticobjects.oo.tests.Assertion;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import org.assertj.core.api.Assertions;

/**
 * Asserts that file, generated by {@link SourceFile} instance, is located at certain 
 * place and has certain contents
 * 
 * @author skapral
 */
public class AssertSourceFileGenerated implements Assertion {
    private final SourceFile file;
    private final Path path;
    private final String contents;

    /**
     * Ctor.
     * 
     * @param file Source file under test
     * @param path Expected path
     * @param contents Expected contents
     */
    public AssertSourceFileGenerated(SourceFile file, Path path, String contents) {
        this.file = file;
        this.path = path;
        this.contents = contents;
    }
    
    
    @Override
    public final synchronized void check() throws Exception {
        file.generate();
        Assertions.assertThat(Files.exists(path)).isTrue();
        final String contents = new String(Files.readAllBytes(path));
        Assertions.assertThat(this.contents).isEqualTo(contents);
    }
}
